# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb8ca3a94f37136894f9752ae29c1bb64560cd5c4e006668c4b4fe388e9e9457561a911b4423e0e49277168aaef8f019dec4fbcdb347eaf4d45aa43b75fc1387

test:
  secret_key_base: 5ed677938cca0cf258e8c0f6e6e8802c763ef254228c256d3f763f494d1b2d14d4cb7b29f780c2b890e757c53892746881e80e23c64d8797058258699a4851fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
